### ISSUE TITLE
Professional Mode force close

### ISSUE THREAD

**Issue by pierx** [DineshSolanki/FoliCon#6]
Hi there, 
Thanks for the update. 
However on the latest version, the professional mode just keep force closing once make icons button pressed.  Already tested on windows 1909 and 2004 update.
Also the zip file are content are bit different on sourceforge and github (which contain the map.xml) and only the github release that able to launch here.

**Comment by DineshSolanki** [comment]
Could you please share me a video of you trying that.

**Comment by pierx** [comment]
![ff](https://user-images.githubusercontent.com/11854637/84364774-1aa32400-ac03-11ea-9414-10fb73a95453.gif)

Here is a log from windows event viewer, hope it helps
https://pastebin.com/SFJPzkBV

**Comment by DineshSolanki** [comment]
Hey @pierx the event log was helpful, thank you. I realized that the configuration file was missing from the release, and SourceForge might have also auto picked the wrong release. can you please check if the issue is fixed.

**Comment by pierx** [comment]
Thanks for the quick update. It works nicely now!

**Comment by pierx** [comment]
Hi there Dinesh, sorry for bothering you again.  Here's a force close log when using the professional mode, it happens when the search start and during fetching the images. 

------------------------------------
Application: FoliConv3.1.exe
CoreCLR Version: 4.700.20.56602
.NET Core Version: 3.1.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FoliCon.ViewModels.ProSearchResultViewModel.NVN2CGxb6J(String  , Int32  )
   at FoliCon.ViewModels.ProSearchResultViewModel.bhs2wC4M3F()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at Prism.Services.Dialogs.DialogWindow.Prism.Services.Dialogs.IDialogWindow.ShowDialog()
   at Prism.Services.Dialogs.DialogService.ShowDialogWindow(IDialogWindow dialogWindow, Boolean isModal)
   at Prism.Services.Dialogs.DialogService.ShowDialogInternal(String name, IDialogParameters parameters, Action`1 callback, Boolean isModal, String windowName)
   at Prism.Services.Dialogs.DialogService.ShowDialog(String name, IDialogParameters parameters, Action`1 callback)
   at FoliCon.Modules.DialogServiceExtensions.ShowProSearchResult(IDialogService dialogService, String folderPath, List`1 fnames, DataTable pickedTable, List`1 imgList, DArt dartObject, Action`1 callBack)
   at FoliCon.ViewModels.MainWindowViewModel.rYNbCoIVj()
   at FoliCon.ViewModels.MainWindowViewModel.sAOU1Kufm()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at FoliCon.App.Main()

**Comment by DineshSolanki** [comment]
@pierx no problem, I was aware of this issue and fixed it 3 days ago(cfaa8514a22a44869a52b35463171dce55476169 ), forgot to push the code, I might release it tomorrow or the day after. Thank you.

**Comment by DineshSolanki** [comment]
It seems the issue is causing trouble because of recent changes in DeviantArt API -
The parameter that Folicon uses to get only folder icons has no effect now, and sometimes the returned result is not downloadable content. as Stated on DeviantArt -
**GET category_path (string) : optional | Category path to fetch from. This parameter is deprecated,  it has no effect on the results and it will be removed in future versions.**

It might take a while until I find a solution to this. without this, Professional mode is almost broken.

**Comment by DineshSolanki** [comment]
#15

**Comment by DineshSolanki** [comment]
The issue has been fixed for now, and I'm looking for a way to search efficiently in professional mode.

**Comment by pierx** [comment]
Thank you very much Dinesh for the update and also for the new feature!
Regards
